### PR TITLE
Update Stackage tag to 13.19

### PR DESCRIPTION
**Pull request by blitz**
hamtsolo still builds fine with 13.19. Only on 14, the libiserv problem appears. So I propose updating to 13.19 for the time being.

The upstream issue preventing updating to lts-14.x is this: https://github.com/input-output-hk/haskell.nix/issues/269

### CODE REVIEW

**Comment by tfc** [comment]
@mnapierkowski can you do us a favor and test if this works as @blitz and i are currently on Nixcon?

**Comment by blitz** [comment]
@tfc The only way to get this working in Travis is to enable caching. Even locally this builds for more than an hour and I don't see a way to increase the total Travis CI time limit of 50 min. I also can't donate a Hercules CI worker, because GHC keeps crashing on the one box I have available.

Paths forward:
- disable Travis and find a working Hercules CI agent,
- use a Nix image, but then build via stack,
- find a cachix repo that holds precompiled Haskell packages and GHCs.

I'm leaning towards the second option.

**Comment by blitz** [comment]
> @mnapierkowski can you do us a favor and test if this works as @blitz and i are currently on Nixcon?

I've verified that the Nix-built binary works.

**Comment by blitz** [comment]
@tfc The "stack on Nix" build succeeds in Travis.

**Pull request merged**
